### ISSUE TITLE
Tables with the Leftmost line of | do not render correctly

### ISSUE THREAD

**Issue by timtjtim** [cakebake/markdown-themeable-pdf#100]
I like to format my tables like so:

```
| cdID  | artID  |
|-------|--------|
|     1 |      1 |
|     2 |      1 |
|     6 |      5 |
|     8 |      7 |
|    10 |      8 |
```

It mis-formats these, and I have to change it to this:

```
 cdID  | artID  |
-------|--------|
     1 |      1 |
     2 |      1 |
     6 |      5 |
     8 |      7 |
    10 |      8 |
```

**Comment by cakebake** [comment]
Your second example is not valid. The first one renders correctly in v2 (I have not testet it in current version, because I make a rewrite of the whole package).

**Comment by timtjtim** [comment]
I’m aware the second one is not valid - that’s why it’s annoying I had to change it to work!

I will wait for v2.

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
