### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by M-Fabian** [cakebake/markdown-themeable-pdf#103]
I did not find a changelog. I would encourage you to write one. You may find inspiration here: https://keepachangelog.com/

**Comment by cakebake** [comment]
I was always too lazy to write a changelog when versioning with GIT.

But since the project has now reached a certain size (and users), that makes sense and I had it for the v2 already on the todo. However, the changelog will only start from v2.

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
