### ISSUE TITLE
Table text-align PDF Export

### ISSUE THREAD

**Issue by markus-kraemer** [cakebake/markdown-themeable-pdf#109]
|:----|----|----:| etc. doesn't work in the PDF-export.

**Comment by cakebake** [comment]
Not enough information

**Comment by partnerwerk** [comment]
I am trying to get this table rendered with right aligned columns. But they do not get aligned right. Do they get a css class so I can style them?

```
|   Datum    | Kontostand |
|:---------- | ----------:|
| 17.10.2018 | € 1.986,49 |
| 15.1.2019  | € 1.421,26 |
```

<img width="766" alt="bildschirmfoto 2019-01-18 um 18 38 55" src="https://user-images.githubusercontent.com/13697507/51403540-0a436280-1b51-11e9-81d2-6a6bf2243634.png">

**Comment by cakebake** [comment]
Hello @partnerwerk,

the best way to do this, is to export with markdown-themeable-pdf to HTML and then inspect the HTML.

I've added this issue as ~question for ~v2 and will check the markdown specs for the text-align option. It must also be checked if the used modules support this feature.

**Comment by partnerwerk** [comment]
The HTML output is ok. It looks like this:

```
<tr>
<td style="text-align:left">text</td>
<td style="text-align:left">text</td>
<td style="text-align:right">text</td>
<td style="text-align:right">text</td>
</tr>
```

However the created pdf has no right text align as one might expect from this source.

**Comment by cakebake** [comment]
That's right ... weird behavior ...

Generated HTML

![image](https://user-images.githubusercontent.com/7462226/52210232-ade97e00-2886-11e9-9f05-d10abf14079f.png)

Generated binary

![test](https://user-images.githubusercontent.com/7462226/52210260-cbb6e300-2886-11e9-8cd0-0f4c1e75cf49.jpeg)

..., but I found the reason:

If you need the change immediately, I would recommend you to edit the following file and remove the highlighted code area. Then you have to restart Atom. The package files are locatet in your atom/packages folder. 

- https://github.com/cakebake/markdown-themeable-pdf/blob/master/lib/markdown-themeable-pdf.js#L325-L338
- https://discuss.atom.io/t/atom-config-directory-locations/38862

The code above should prevent ugly table breaks when they span multiple pages. But it did not help, because it's a common Chromium / Phantomjs problem.

The version you are using is no longer being developed. In version 2, everything fits already. This will be published soon.
