### ISSUE TITLE
Style sheet does not support font face

### ISSUE THREAD

**Issue by marekbrezina** [cakebake/markdown-themeable-pdf#117]
Hello, 
it seems to me that the @font-face is not supported during pdf export.. 
I have created a custom style sheet with font definition as seen below, but I was not able to make it work. The file "Rajdhani-Regular.ttf" is placed in the same directory as css. 
I had to install the font in my windows 10 machine. Then it worked. Same behaviour observed in iOS. 
Is there something wrong? 
Thanks for your help. Marek 

@font-face {
    font-family: "RajdhaniRegular";
    src: url(Rajdhani-Regular.ttf) format("truetype");
}
html, body {
    background: #FFF;
    font-family: "RajdhaniRegular", Rajdhani, Courier, freesans, sans-serif;
    font-size: 10px;
    line-height: 1.4;
    color: #333;
    word-wrap: break-word;
    text-align: justify;
	hyphens: auto;
}

**Comment by cakebake** [comment]
Currently, paths in CSS are not resolved. I solve this in v2. In v2, the paths within CSS `@import` and `url(*)` are resolved and converted into base64 data uri's for maximum compatibility.

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
