### ISSUE TITLE
Codeblock colour not rendered in PDF

### ISSUE THREAD

**Issue by judelucien** [cakebake/markdown-themeable-pdf#124]
Hi,

I am using Xubuntu 18.04.2 LTS.

When I successfully convert my Atom (1.35.1) Markdown doc to PDF (1.2.1), the codeblocks do not retain the colour.  The rendered PDF only shows quoted text as orange and language keywords in red.

Should the full range of colour be displayed? 

Please let me know if I can supply any more information.

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
