### ISSUE TITLE
different footer and header in single and double page

### ISSUE THREAD

**Issue by ghost** [cakebake/markdown-themeable-pdf#126]
single page number in footer right side , double page number in footer left side. 
Header is the same. As Latex-Template https://github.com/Wandmalfarbe/pandoc-latex-template

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
