### ISSUE TITLE
font-weight does not change in custom styles.css

### ISSUE THREAD

**Issue by tibohei-tamedia** [cakebake/markdown-themeable-pdf#130]
## Problem/Bug

In `styles.css` when defining a custom font `font-weight` does not work for export to pdf.
```
@import url('https://fonts.googleapis.com/css?family=Quicksand:300,400,500,600,700|Roboto:100,100i,300,300i,400,400i,500,500i,700,700i&display=swap');

html, body {
  background: #FFF;
  font-family: "Quicksand", sans-serif;
  font-size: 10px;
  font-weight: 700;
  line-height: 1.4;
  color: #535353;
  word-wrap: break-word;
  hyphens: auto;
}
```

I tried different fonts (Roboto, Open Sans, Quicksand) and different weights (300, 400, etc.). Changes of `font-family` do work. Markdown markers for `**bold text**`do also not work.

When exporting to HTML changes of `font-weight` are working.

What am I missing? Or is this a bug?

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
