### ISSUE TITLE
There is no "Markdown to PDF" when right click in editor area in Atom

### ISSUE THREAD

**Issue by aakbarig** [cakebake/markdown-themeable-pdf#133]
Hi
I've installed the package, but I can't find any of 3 options mentioned in usage topic.
Try to reinstall it, but same problem.

Can you please review this
Thanks

**Comment by wilves** [comment]
Hi,

Same for me.
Any indication will be appreciated. Thanks
William

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
