### ISSUE TITLE
font size in code block.

### ISSUE THREAD

**Issue by julius1986** [cakebake/markdown-themeable-pdf#136]
Hello. I want to change font-size in all document. I wrote in css 
* {
 font-size: 1.5rem;
}
All fine, but in block of code, it is working wrong.   
``` javascript
let varA = 33;
```

name of variable(varA) does not change the size;

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
