### ISSUE TITLE
Uncaught The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by Coach257** [cakebake/markdown-themeable-pdf#139]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0-beta0 ia32
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [markdown-themeable-pdf](https://github.com/cakebake/markdown-themeable-pdf) package 1.2.1

### Stack Trace

Uncaught The "path" argument must be of type string. Received type undefined

```
At path.js:39

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at Object.getConfigFilePath (/packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:575:28)
    at /packages/markdown-themeable-pdf/lib/markdown-themeable-pdf.js:365:44
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

### Commands

```
  4x -2:47.7.0 markdown-themeable-pdf:export (div.line.cursor-line)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
language-markdown 0.37.0 
markdown-image-paste 2.5.2 
markdown-img-paste 0.4.0 
markdown-preview-plus 3.11.5 
markdown-table-editor 1.1.2 
markdown-themeable-pdf 1.2.1 
markdown-toc 0.4.2 
simplified-chinese-menu 5.3.5 
```

**Comment by baatochan** [comment]
There's workoaround for it in #128. You need to open the folder as a project.

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
