### ISSUE TITLE
Text selection in PDF is not ideal

### ISSUE THREAD

**Issue by AndyOGo** [cakebake/markdown-themeable-pdf#140]
Please open the [Demo PDF file](https://github.com/cakebake/markdown-themeable-pdf/raw/master/tests/Demo.pdf) and start selecting.

This is what macOS Preview does:
<img width="1054" alt="Screenshot 2020-05-17 at 08 55 08" src="https://user-images.githubusercontent.com/914443/82137904-59b8a200-981c-11ea-923d-47fe4de67f46.png">

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
