### ISSUE TITLE
export to pdf problem:line breaking on a inappropriate place when it comes to tables.

### ISSUE THREAD

**Issue by Tlfebook** [cakebake/markdown-themeable-pdf#142]
![ce498a5ec1765e1e56f984f8147ca5a](https://user-images.githubusercontent.com/25795954/87004560-3264cc80-c1f0-11ea-8a50-c8d4d74cc768.png)

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
