### ISSUE TITLE
Request to call pdf-view-plus

### ISSUE THREAD

**Issue by RandyVogel** [cakebake/markdown-themeable-pdf#144]
Hi! I'd like to use pdf-view-plus instead of pdf-view, but the "Open PDF in Atom Workspace" preference toggles only ON/OFF; any chance this could be made to work with pdf-view-plus (and perhaps fall back to pdf-view in the absence of the newer package)?

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
