### ISSUE TITLE
PDF optimization / compression possible

### ISSUE THREAD

**Issue by jbaksta** [cakebake/markdown-themeable-pdf#34]
Any thoughts about optimization / compression for PDFs? I'm writing some documents that are 15-40 pages in length and the resulting PDFs are starting to be quite large (order of 10MB on the lower end). I've not inspected the resulting PDFs too closely, but the same HTML output is approximately 30KB. Perhaps this has to do with extra included styling? Running Atom on OS X right now.

**Comment by cakebake** [comment]
Strange. My Testfile with 142 Pages has a filesize of 536kb... If you embed images, you should compress it.

Example File: https://github.com/cakebake/markdown-themeable-pdf/blob/master/tests/LongFileWithTables.pdf

Unfortunately, I can not change the compression. The whole is printed by Webkit as a file. Since there are far as I know no options for compression.

**Comment by baires** [comment]
Im on the same boat that @jbaksta Simple `md`, no images, just plain text (170 lines) and all I get is a pdf > 3.5 mb. Any ideas?
