### ISSUE TITLE
Feature Request: Optional specified output path

### ISSUE THREAD

**Issue by jykong** [cakebake/markdown-themeable-pdf#44]
It would be nice to have settings option to specify output path to somewhere other than the directory of the input file.

For example, if the default is `$INPUT_FILE_PATH$/$INPUT_FILE_NAME$.pdf` allow alternatives like `$INPUT_FILE_PATH$/pdf/$INPUT_FILE_NAME$.pdf` or `~/some/other/path/$INPUT_FILE_NAME$.pdf`

**Comment by cakebake** [comment]
Useful for all it would be if there was selection window, through which you can select the location. I would be here for a PR!

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
