### ISSUE TITLE
Footer disappears when setting Page border size to 0cm

### ISSUE THREAD

**Issue by mkismy** [cakebake/markdown-themeable-pdf#51]
Hi,
I have a problem that if the "Page border size" is set to 0cm, the page footer disappears.

![screenshot](https://cloud.githubusercontent.com/assets/8445575/16837253/1d890c00-49fd-11e6-8211-6f79b0c8482f.png)

**Comment by cakebake** [comment]
This is fixed in v2. You can then adjust the border individually for top, right, bottom and left.

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
