### ISSUE TITLE
Citation Support

### ISSUE THREAD

**Issue by guilherme-salome** [cakebake/markdown-themeable-pdf#53]
I'm using R markdown citation notation:

```
This is a citation (Someone 2011)[^1]

[^1]: Someone bla bla bla information on the paper
```

But it is not supported by your awesome plugin. Do you have any plans on supporting anything like that?
Thanks you! :D

**Comment by cakebake** [comment]
#76

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
