### ISSUE TITLE
Support for Emoji

### ISSUE THREAD

**Issue by prantikv** [cakebake/markdown-themeable-pdf#54]
Markdown for github has support for emojis see here [http://www.webpagefx.com/tools/emoji-cheat-sheet/](http://www.webpagefx.com/tools/emoji-cheat-sheet/)

Also here [https://github.com/github/gemoji](https://github.com/github/gemoji)

So : + 1 : is converted to :+1: 

Would love to see this or something along those lines in the app.

-Thanks

**Comment by tatoosh** [comment]
Wanted to add the same suggestion. 
I am using :question: :mag: :e-mail: and :calling:

**Comment by cakebake** [comment]
Stands on the Todo - I just have to come to :+1:

**Comment by simonmcl** [comment]
This would be great. I was using ✅  and ❌  in a table to say whether or not the feature was supported. Looking for a work around now with some images

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
