### ISSUE TITLE
table of contents hyperlink

### ISSUE THREAD

**Issue by qingkouwei** [cakebake/markdown-themeable-pdf#65]
Is it support table of contents auto skip content?

**Comment by cakebake** [comment]
Not up to date, but it is on the agenda

**Comment by ghost** [comment]
Hi,

I was wondering if this is fixed in v1.2.1? I still get invalid TOC links when converting to PDF.

 If not, is there a way for me to sort of install the "rewrite" branch to have this feature?

Thanks

**Comment by cakebake** [comment]
Hi @ofmonzon,

sorry no, I have not been able to release v2 yet, as Chromium has header and footer issues.

You could install package to ~/.atom/packages. Hope this helps a little bit: https://discuss.atom.io/t/manually-install-package/9251/7

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
