### ISSUE TITLE
PDF Internal document links always popup security warning

### ISSUE THREAD

**Issue by dirkdejager** [cakebake/markdown-themeable-pdf#78]
Hi,

Thanks for an awesome plugin. but whenever I try and use an internal document link such as:

[Background](#background)

## Background

the PDF version  (When using Adobe Reader) gives me a security warning asking me whether I would like to allow this. No matter whether I click Allow or Block, it will always ask me the same question over again and the link does not work.

Any chance you could resolve this?

Thanks again!

**Comment by bouncydot** [comment]
Would be very interested in this feature, as well.

**Comment by cakebake** [comment]
This should be fixed in v2.

Demo: [links.pdf](https://github.com/cakebake/markdown-themeable-pdf/files/1832688/links.pdf)

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
