### ISSUE TITLE
[Bug] Inline code is not wrapped

### ISSUE THREAD

**Issue by noraj** [cakebake/markdown-themeable-pdf#79]
The following code:

````markdown
`38029ecd84f18db3e425967dbb75e4bb8c02ff6a3f1c546446532069432a6c854a0ee12d35282751360686ec666832c6b9dda169298dcb923b09b0d7f72d4d7a`

```
38029ecd84f18db3e425967dbb75e4bb8c02ff6a3f1c546446532069432a6c854a0ee12d35282751360686ec666832c6b9dda169298dcb923b09b0d7f72d4d7a
```

38029ecd84f18db3e425967dbb75e4bb8c02ff6a3f1c546446532069432a6c854a0ee12d35282751360686ec666832c6b9dda169298dcb923b09b0d7f72d4d7a
````

render as:

![](http://i.imgur.com/lzLXHdH.png)

Normal text or code block are correctly soft-wrapped but not inline code.

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
