### ISSUE TITLE
page-break improve documentation

### ISSUE THREAD

**Issue by roccomuso** [cakebake/markdown-themeable-pdf#80]
Add the explicit example into the doc:

```
<div class="page-break"></div>
```

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
