### ISSUE TITLE
HTML <a> tag not work in header and footer

### ISSUE THREAD

**Issue by jzoe** [cakebake/markdown-themeable-pdf#95]
I try to add link in the `header.js` and `footer.js`, but all not work for me! Is it a bug ?

My footer is like this:

```js
module.exports = function (info) {
    var dateFormat = function () {
        return (new Date()).toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'short',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        });
    };
    return {
        height: '1cm',
        contents: '<div style="float:left;">Page {{page}}/{{pages}}</div><div style="float:right;">&copy; Copyright by <a herf="https://github.com/cakecake" target="_blank">CAKE. corp</a> released at ' + dateFormat() + '</div>'
    };
};
```

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
