### ISSUE TITLE
Feature Request: Support Multiple Shortcuts for convert to PDF, HTML

### ISSUE THREAD

**Issue by flakrat** [cakebake/markdown-themeable-pdf#99]
I routinely have to convert my markdown files into both PDF and HTML files.

Rather than having to go to settings to change the conversion type each time, it would be nice to be able to optionally support conversion to each type by a separate type by a different shortcut.

**Comment by cakebake** [comment]
Hello, sorry, but I will no longer maintain the project.

### This project is archived because the owner no longer uses the Atom Editor.

It would be very good to find a new owner for this project, who will take care of updating and expanding the Atom package. A new version based on Chrome Headless has already been [prepared in a feature branch](https://github.com/cakebake/markdown-themeable-pdf/tree/rewrite).
